### PR TITLE
chore: bump koa-send@4

### PR DESCRIPTION
**Pull request by Nicholaiii**
Tests are passing

### CODE REVIEW

**Comment by coderhaoxin** [comment]
#99 

we need catch and handle 404 error from `koa-send`

**Comment by jtmthf** [comment]
@coderhaoxin What specifically about handling 404 error's is blocking this PR from being merged? Other than the current tests passing is there some additional functionality required?

**Comment by adrianblynch** [comment]
Interested to know when this happens.

**Comment by neoziro** [comment]
Can you please merge this PR?

**Comment by VladShcherbin** [comment]
Can this be merged?

cc @coderhaoxin

**Comment by jtmthf** [comment]
In the meantime, I suggest looking into using koa-static directly as koa-send is only a thin wrapper around it. Works pretty well and is one less dependency to worry about.

**Comment by neoziro** [comment]
@jtmthf you mean using koa-send without koa-static?

**Comment by jtmthf** [comment]
@neoziro Sorry if I wasn't clear earlier, I was typing out the message on my phone. Most of the logic for `koa-static` happens to be in `koa-send`. With a thin wrapper around `koa-send`, you can implement your own static file server rather easily. In fact I believe this meshes well with the Koa ethos of easy to implement async middleware.  To get you started, here's an example ripped from [reactql](https://github.com/reactql/kit) which shows this off quite elegantly.

```js
// Static file middleware
export function staticMiddleware() {
  return async function staticMiddlewareHandler(ctx, next) {
    try {
      if (ctx.path !== '/') {
        return await koaSend(
          ctx,
          ctx.path,
          process.env.NODE_ENV === 'production' ? {
            root: PATHS.public,
            immutable: true,
          } : {
            root: PATHS.distDev,
          },
        );
      }
    } catch (e) { /* Errors will fall through */ }
    return next();
  };
}
```

This example is pretty specific to `reactql`, but you can see that it's fairly trivial to wrap the functionality of `koa-send` in your own middleware. If you need further assistance, I would be glad to help 😃

**Comment by coderhaoxin** [comment]
I submit a PR to upgrade to koa-send@4

https://github.com/koajs/static/pull/102

**Comment by VladShcherbin** [comment]
@jtmthf that's the whole point of this package - a thin middleware you can quickly add and you are good to go. 😏

**Comment by coderhaoxin** [comment]
`4.0.0`

**Comment by VladShcherbin** [comment]
@coderhaoxin Thank you! :smirk:

**Comment by neoziro** [comment]
Thank you!

**Pull request closed without merging**
