### PR TITLE
Es6 const

### PR DESCRIPTION
**Pull request by tejasmanohar**

### CODE REVIEW

**Comment by jonathanong** [comment]
added

**Comment by tejasmanohar** [comment]
added?

**Comment by jonathanong** [comment]
to the repo/org!

**Comment by tejasmanohar** [comment]
ohhh thanks! gotcha now, was confused since it was on this PR haha.

**Comment by tejasmanohar** [comment]
@jonathanong so is it fine if I merge this, or is there one person who handles all the merging? any contributing guidelines I need to keep in mind?

**Comment by jonathanong** [comment]
i'm :+1: this :) you can merge

**Comment by coderhaoxin** [comment]
:clap:

**Pull request merged**
