### PR TITLE
Update koa-send dependency

### PR DESCRIPTION
**Pull request by pierreburgy**
Update koa-send dependency

### CODE REVIEW

**Comment by coderhaoxin** [comment]
Since `format` option defaults to true in `koa-send@3`, this will be a broken change.

https://github.com/koajs/static/issues/53

Maybe need a major bump.

**Comment by pierreburgy** [comment]
@coderhaoxin I totally agree for a major bump.

**Comment by pierreburgy** [comment]
Up

**Comment by coderhaoxin** [comment]
https://github.com/koajs/static/pull/66

**Pull request closed without merging**
