### PR TITLE
add prefix option

### PR DESCRIPTION
**Pull request by kimjuny**
see readme.md

### CODE REVIEW

**Comment by coderhaoxin** [comment]
we can use https://github.com/koajs/mount for this :)

**Comment by kimjuny** [comment]
@coderhaoxin This simple modification is originally from https://github.com/wssgcg1213/koa-static-plus, it makes sense and is good to use. Unfortunately it uses generator(deprecated for node now).

**Comment by coderhaoxin** [comment]
@kimjuny SGTM :)

but can you submit PR to https://github.com/koajs/send ?

**Comment by kimjuny** [comment]
ok. I'll close this.

**Comment by kimjuny** [comment]
ok. I'll close this.

**Comment by Dragon-Rider** [comment]
Hi there, I think @kimjuny's PR is very usefull. Because it can help us reduce one more middleware(mount) just like koa-route's 'prefix' option. So please think about it :)

**Comment by coderhaoxin** [comment]
@Dragon-Rider `koa-static` is a wrapper of `koa-send`, so it's better to add this feature to `koa-send`.

https://github.com/koajs/static/pull/110#issuecomment-321244191

**Pull request closed without merging**
