### PR TITLE
yield next anyway

### PR DESCRIPTION
**Pull request by ibigbug**
Do not break the middleware chain.

### CODE REVIEW

**Comment by jonathanong** [comment]
why? this could break a lot of things

**Comment by ibigbug** [comment]
I'm working on an auto-test tool for koa-based apps. However when a url was matched by `static`, other middleware including mine won't work anymore. And may I know why you design it like this ?

**Comment by jonathanong** [comment]
set the `defer: true` option so that `koa-static` matches last!

**Comment by ibigbug** [comment]
The problem is when static content was sent the middleware chain gets broken without a `yield next`, so no one can touch the content :(

**Comment by jonathanong** [comment]
oh interesting. maybe it's better if you used `koa-send` directly

**Comment by ibigbug** [comment]
OK

**Pull request closed without merging**
