### PR TITLE
add repath option

### PR DESCRIPTION
**Pull request by zyao89**
see readme

### CODE REVIEW

**Comment by jonathanong** [comment]
what's the use-case for this?

**Comment by zyao89** [comment]
> what's the use-case for this?

eg：
```
// file tree
public
 | -- hello.txt
```
```js
const serve = require('koa-static');
const Koa = require('koa');
const app = new Koa();

// $ GET /static/hello.txt
app.use(serve('public', {
    repath(path, ctx) {
        return path.replace('/static', '');
    }
}));

app.listen(3000);

console.log('listening on port 3000');
```

**Comment by jonathanong** [comment]
you can just use http://github.com/koajs/mount

**Comment by zyao89** [comment]
OK, thks

**Pull request closed without merging**
